
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "git::https://github.com/guicrocetti/terraform-modules.git//modules/iam_project_member"
}

include "root" {
  path = find_in_parent_folders()
}

dependency "service_account" {
  config_path = find_in_parent_folders("service_account")
  mock_outputs = {
    sa_email = "sa_email@project_id.iam.google.com"
  }
}

inputs = {
  roles  = ["roles/secretmanager.secretAccessor"]
  member = "serviceAccount:${dependency.service_account.outputs.sa_email}"
}
