
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "git::https://github.com/guicrocetti/terraform-modules.git//modules/external_secrets"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

locals {
  account_vars          = read_terragrunt_config(find_in_parent_folders("account.hcl"))
  service_account_name  = local.account_vars.locals.service_account
  project_id            = local.account_vars.locals.project_id
  service_account_email = "${local.service_account_name}@${local.project_id}.iam.gserviceaccount.com"
}

dependency "k8s" {
  config_path = find_in_parent_folders("k8s")
  mock_outputs = {
    cluster_name    = "cluster_name"
    cluster_server  = "cluster_server"
    cluster_ca_data = "cluster_ca_data"
  }
}

inputs = {
  cluster_name                   = dependency.k8s.outputs.cluster_name
  cluster_endpoint               = dependency.k8s.outputs.cluster_server
  cluster_ca_certificate         = dependency.k8s.outputs.cluster_ca_data
  service_account_name           = local.service_account_name
  service_account_email          = local.service_account_email
  repo_username                  = "guicrocetti"
  repo_name                      = "argocd-cloud-infra-test"
}
