
# # This is a Terragrunt module generated by boilerplate.
# include "root" {
#   path = find_in_parent_folders("root.hcl")
# }

# include "envcommon" {
#   path   = "${dirname(find_in_parent_folders("root.hcl"))}/_envcommon/secret_manager.hcl"
#   expose = true
# }

# terraform {
#   source = "${include.envcommon.locals.base_source_url}?ref=${include.envcommon.locals.version}"
# }

# inputs = {
#   secret_name = "repo-password"
#   label       = "argo_repo_password"
#   SECRET_DATA = get_env("TF_VAR_ARGOCD_GITHUB_TOKEN")
# }
