
# # This is a Terragrunt module generated by boilerplate.
# terraform {
#   source = "git::https://github.com/guicrocetti/terraform-modules.git//modules/iam_google_organization_member"
# }

# include "root" {
#   path = find_in_parent_folders("root.hcl")
# }

# dependency "service_account" {
#   config_path = find_in_parent_folders("service_account_adm")
#   mock_outputs = {
#     sa_email = "sa_email@project_id.iam.google.com"
#     sa_id    = "projects/project-id/serviceAccounts/service-account-name@project-id.iam.gserviceaccount.com"
#   }
# }

# inputs = {
#   org_id       = "416088232210"
#   role_name    = "roles/editor"
#   member_type  = "serviceAccount"
#   member_email = dependency.service_account.outputs.sa_email
# }
