
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "git::https://github.com/guicrocetti/terraform-modules.git//modules/iam_workload_id_oidc"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

inputs = {
  pool_provider_id = "github-ci-gitops-provider"
  pool_id          = "github-ci-gitops-pool"
  oidc_issuer      = "https://token.actions.githubusercontent.com"

  attribute_condition = "attribute.repository.startsWith('guicrocetti/')"

  mapping_attributes = {
    "google.subject"       = "assertion.sub"
    "attribute.actor"      = "assertion.actor"
    "attribute.repository" = "assertion.repository"
  }

  pool_display_name          = "Github Workload Identity Pool"
  pool_description           = "Identity Pool for Github"
  pool_providrr_display_name = "GitHub Provider"
}
