
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "git::https://github.com/guicrocetti/terraform-modules.git//modules/iam_service_account_member"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

dependency "service_account" {
  config_path = find_in_parent_folders("service_account_adm")
  mock_outputs = {
    sa_email = "sa_email@project_id.iam.google.com"
    sa_id    = "projects/project-id/serviceAccounts/service-account-name@project-id.iam.gserviceaccount.com"
  }
}

dependency "workload" {
  config_path = find_in_parent_folders("iam_workload_id_github_oidc_adm")
  mock_outputs = {
    pool_name     = "pool_name"
    provider_name = "provider_name"
  }
}

inputs = {
  service_account_id = dependency.service_account.outputs.sa_id
  roles              = ["roles/iam.workloadIdentityUser"]
  member             = "principalSet://iam.googleapis.com/${dependency.workload.outputs.pool_name}/*"
  condition = {
    title       = "restrict_by_tag"
    description = "Allow access only if tag 'environment' is 'test"
    expression  = " resource.matchTag(' environment ', ' test ') "
  }
}
