
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "git::https://github.com/guicrocetti/terraform-modules.git//modules/dns_record_set"
}

include "root" {
  path = find_in_parent_folders()
}

dependency "loadbalancer" {
  config_path = find_in_parent_folders("loadbalancer")
  mock_outputs = {
    loadbalancer_ip = "0.0.0.0"
  }
}

inputs = {
  dns_zone             = "guilherme-iot-basics-com"
  sub_domain           = "argocd"
  dns_name             = "guilherme.iot-basics.com."
  loadbalancer_address = dependency.loadbalancer.outputs.loadbalancer_ip
}
